### ISSUE TITLE
用FormBrowserServer方法时出现错误

### ISSUE THREAD

**Issue by bingdengtan** [dathlin/OpcUaHelper#9]
using (OpcUaHelper.Forms.FormBrowseServer form = new FormBrowseServer())
            {
                form.ShowDialog();
            }
在地址上填上我本地的OPC UA server 地址，点击Connect（我的OPC server是Prosys OPC UA Simulation Server）, 出现以下错误，请帮忙看看，谢谢！！

System.Reflection.TargetInvocationException
  HResult=0x80131604
  Message=Exception has been thrown by the target of an invocation.
  Source=mscorlib
  StackTrace:
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at System.Windows.Forms.Control.InvokeMarshaledCallbackDo(ThreadMethodEntry tme)
   at System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Forms.Control.InvokeMarshaledCallback(ThreadMethodEntry tme)
   at System.Windows.Forms.Control.InvokeMarshaledCallbacks()
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.RunDialog(Form form)
   at System.Windows.Forms.Form.ShowDialog(IWin32Window owner)
   at System.Windows.Forms.Form.ShowDialog()
   at WindowsFormsApp.Form1.Button1_Click(Object sender, EventArgs e) in C:\Users\bingdeng tan\source\repos\WindowsFormsApp1\WindowsFormsApp1\Form1.cs:line 90
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.Run(Form mainForm)
   at WindowsFormsApp.Program.Main() in C:\Users\bingdeng tan\source\repos\WindowsFormsApp1\WindowsFormsApp1\Program.cs:line 19

Inner Exception 1:
InvalidCastException: Cannot cast an absolute ExpandedNodeId to a NodeId. Use 
ExpandedNodeId.ToNodeId instead.

**Comment by dathlin** [comment]
我也不知道啊

**Comment by yb123speed** [comment]
我也遇到了这个情况
![](data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAY8AAAChCAYAAAA/SzMVAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAABiSSURBVHhe7Z27jiTHlYZpyqMnh4boUI9BaBdYuuNoLXlahwBHRoOGQI+iRWAfYI1BE7REOnyA6bEooC0CU8bIIGhNY2hwIIDA2DJy88Ql48SJS2bUpWu6+zM+TFdmXE6ciPz/iqjqnnd+97v3pw8//AMAAMBmMA8AABjmndpFAACAHuw8AABgGMwDAACGGTq2+vz7V9ObN29W+Of0TaXuhx9+MX3/6tX0/ee1e3Wkv1fff1G955E2bX+1fuRaHueLF//MXid03VZb9XGs56cWa7qux+vbGssXADwMfvjhh4JauVMytPMoxPzzf0yvXnyryogYtsxj5ptZsF/9Y/q8dq/CqnkU/Qttcc/KSyzhZ+nnxTdSxtSttV/t09OP1+RG+q8aTImPDQDAI2bxn//xX459zOPTTz9d6gnyerTMac1ji0AuZvLt9KJ2v6DTvmtrwDx03YVQt7jvr0sOatelzfKeJY+9a4yBZGwAAB4R80PMQ+iZw5pxCKc9tloVyNkwOjuRwqwM37yo7RLEPHwsheha8wg/J4FWxpPFHq+X8eoY+vGWxiplv3lh86eY48M8AMAign6oeQg1k9hiHMLJdx498T/IPKRv/ZnA0lcUevl3FuDQfi7S8/3v13ceqW/f5ovZKKyQbzePwNxuNC1B4qqaQ5FbAACPiPoxzEOwZqFpGYcwbB6Z0G0wj7pAK6rivkJ8R/4iCfznsxl4EY/m4WOQcotYD+488n79dSv2xe4nq1Mnr18v48hyCwDgEWE/lnkINQPpGYdw0mMrKd9/J97ZeSzircR5IZpUrK/byc0jo/FuPpmHYu7f7jxim9pAMvMIlNfm+PRxXoP1fAEAePOw1MptZS/zGNl5FEcsKzuPqihvwJnU3K4X02/nNhtHO6Gs7EDS/W3m4foojM/j2uqYhx5nNIqhndPIbqtlrgDwILEir6mVX6NmHJGegQyYR24Mjq55VMqvEY590lFUeifuhbbSntuhWGHvmIcT5fy+MyBrTl3ziNSu13YZ9Z2HNWM9XofEi3kAQAMR+Nr1rVjjkNe1a7W624+tRKStkPXMQ8pn9/o4czDtF2LqRHgup3cP7md/PS+rkbjENOo7mJZ55LuAmnlYU/D9lHEMmsdicr0xAcBDR8S9dn0LPZPYYiCbdx5W6BzRPJTYpSOZxrv/AUrzSEg89p4zkxiHxpqYjreGjKG58wgGFolthzZr5tQyD0tvvAAAFhH22vU1tpjDWpmhzzwAAODtQUS9dv024E+yAwDAMOw8AABgGMwDAACG4dgKAACGYecBAADDOPP44IPfAwAAbMYdW9VuAAAAtGDnAQAAw2AeAAAwDMdWAAAwDDsPAAAYBvMAAIBhOLYCAIBh2HkAAMAwmAcAAAzDsRUAAAzDzgMAAIbBPI7N5c7/97S7r9zry538d7U309VFpeyG+w+SkMObq4v6fbg3PH76cnr9/Mn0qHJvX07RJpTscWz11bSL/393YHdZK7eNi6ubWxLPi+nq5haE+ijmUeb4ECH1feymy3jt4tl0Y9o/p4EVa+Bk5vFoevL8x+np4/ivuvfoyfT8tcrHy6fT46wunALM4+4yuPMoRU04xDxu7533ecxjjWL8sb5hfyGN4357zePW1oAYxI+zKcR/w/VHT55Pr9+8np4/ebSUlWs/Pv1LqnvL3JYAurGf0SjPax7yJuL19PKM83yXGTOPKGw3z6YLdU3MwwtAbiSZKBjBurn6KoiaYhHc3KQW4YxtSP+LyIb2lejWzcyaR+xjFlVV1/dVMRrd93I/osrFtlo7D52HuUx+P407N4s5V1lcEdWuoMYh7C4bO5hsLKq+6j/mMM5rMQem3JY5u3Q7DH3fjmdG8hbGoXPgdyepXLqn5uoyz20W19z//85CeTOLykX414mL23HkxvE2gHnsD+ZxO4wdWy3iZERL36s8tBdGWIS2eZRlBSdSRrgWbm7MdfUue8EaQr2fWDeK1SJSmaBV6kYhNnlomUNOuF/k0NLpt5KbVfPQ2PjltY0nvlZ486iPqztnbszbzMMaR8Tfr7ThMDmP4zNsEs/HT6eXS7svl+OuWPdyFqvY7yJEzpTmspeqrulHRC7We7PsfLyglddTPc9fpqcvY5k3SSyz4zddNy8vceb9q9gzynru+obxZTRy6IX+u+k7NWYdRxajbj9rT40/1Imv9c9LvdfPpyeP8nGlmEz+19bGA2bw2Kp8UMt3nkG4tQBEAamIYvHO3ApWqJuLXuhjeW3FecQ84mtz38Ts46y1a8Zg4q/eW4QsjyGKZMppn1rbUXATcVwq9iVvCiWuvt1IqhevF32MzNmMbScbh2rP37fzlu77mNOajHmL7W/J47p5zCKzS/e1GLm6cz9R7NxrJ0xz2SjisW2zw3GiWIihFVUlehle+Mr7s/BdX/v+59d6bK321sb/+OkufTa0CO/888r4cto5dHnQJqfb0f2Fug6Tq5iPOA+2/WzcWZvlzkPK29e1vMGweXjsO8H4kPrr/iHPBSE94B4rJEkYWu8ynTBFISrEN7ZXEcoFK0Kl0dRjlvuhbBTHYjxCqGeEVLcZx5bEN4+pvG/p9LuMJ7DkSI8jtFPk0aDMpYy1zO3YnJXjtGsgN49ynvJreQ51+8cxD6H+brSo64QviJr+WbXhhUnEzgptLmRd0WqJakDqLrHGck5wU+yx7JbxuzKxvSja3fGluol6DmvjTALuTUHvVOJ9W0ePQ98vynbNI/ZnWMnPQ2X42Cp7II1QRqG4uXpmxDagRCmKScs8qgJaCJEVlrbAWaFeN48Yy/w6nKXXTLKot8E8Ul5iDKGuyk8ufP4zj26/sWzsf+ln3Dx8u5HYfmynnJtNc1bMURpjMY7MPOy8pfs+/vJ+jGeLeZQimOOFMwm9FqlCeM9tHsEgFjGslItGENsuxqBxY7BHYlvGF695ejksx1lpJ8QRjfC05mHnBVrs94G5IYlGeJDDZxDLw6tNI5KZR8CJXRRUTRCeUfPoitC6ecT+bubxlOUsoV7MUcU8qnlwlMJnkTFs6leTmYfH5aIRh5svHb8ZS60PP8cb5qx1f8lRQPUb11UrJ77vNfMIsTWMUhCBse9uRYzk21bu3iKu4Z1peF0I74C45u3OOOFP5QvRy/BxaNH77sp/EWA5Ngv9LYL73bPFRHTcxRg0lZj22Xn0cpi1Kfd1n4+/m66ikOv+TFw2Hzp3bnyNnNRizmOV+tfTNWZSZcw8KkKQjMOTHvQkDmW9xr0oUq3y8fptmYcW3hibQ4nlHMuVrmcEt2hTCXD60oDuMy8TKUS61a+6v4hl1mfHPOYdo78e40njX+bZ9OPjmtkwZz5ewYxX162Yh2ANZOn3COYhOJFR7S/CHd/1uusvp+urjvAOmMciZEufuuyME0i53ngnbOLydYMwx3pX1+lddrV8fr0U/jzGl9fPBsanMH3rHHqhfzZd67iX8Zr+Vdt2vqwBJOPt5CRrJ44l77Nt4HD8v20VxSUTW3iwFIYPAPeBvT4w7xGPINI7Q3jQYB4A95KjmUd2rIBQQATzALiXHO3YqvpZBwAA3EuOfmwFAAD3n/tjHu54ZL9dj3xOY781dmzczuwIXyI4VjtvH/KtKPMtrL04Vjv3m73X/AHP2WaO1sfdWQvH0qDb1IfBYyv11dW37fONY5lH89tishD3X9CbJ1X67+T0/OZRfjU2IrHt/wBsfdB9/+0vZGxsp5Hno76RiGtJ8bZ8keQ45nGitbD5WV6b69r9ioZFtj6f1bKH6cPW+Vh7/m9THwZ3HmsP7hk5pnnYX3J0HLY4Nk/qAeZxOwvHrwH3i5MmTul/f+HdKPp3zTw6c3lOjmkeR18LJzUPxT6acSJ9wDzOyVHNY34Q5N+svcMWx+ZJXRGcXju3s3DiGgjCoRa89L+3YGwVfczjKBzTPI6+Ft568zi+PtxJ89jn2Kp8cP31FLQkMiQjJFv/Xw754ELdcC8lMEy8/j8asgcxr+dRk+cWRrqXxewmXtdT/aoHXiY0H1O+ONz9pQ2zSE3/DjVuN8nLPdWu6n9LO5E8FjVeM9buAs3Kth4EtQZcbGnchWDY2E3cNuY8h34NxXup3XIN9ttpYPMckLaWvrL4t8RmaPTh5z7l18XvysWx6fbNWBpzFEVD52Lzmp/JcpjF3HvOjrUWen0IrXzL9Tw/Q2vBxVRZ571Y1Zy6vpZ7EkveVh5Lbx49Ol8tfYjzvLRjYxWy3J6OvXYe9UDTRGYLJyQpJca3EV9fXO1SUrPJDAtmWcj+dXwg8omLydZ19USm2HwfeiJ9u1m8sc8wMb7PvE3bvx9nHnt6eEPeYnkpa+vGPvXPa+0YioWVxSTY9jTzPVVXxqcXc8LHkM1DiDeb9yLPdt7nWJdxzrhYY3kpW9b1feb999vpkOU5kcad95PoxWZwscz5WUj1ln4kT0scvq1szrI5bM+RX/+NvKys+WzeYt3Qj5tf1afvJ8aTj33ftbDeRyvfMo50z9UbWQsuLv18xGvtWLN148rqWFJbdkzZPK7Mhytr66q8pnu+Xlp7Ptas7gk57rGVS1BaQMs1/TpeKxI713PEpOYLQ0gPS3kvWwhZewmJO0++J7Ub6qp400LWi6PSv85NZcy6X7ewivhU7LHuSjsWey8bV6NMTlh8MaZqObsG/AKWfqTt2F+1n2U8tXWkchoeyjw/cSy67ko7y7UKldwKOmduDEu/oUw3trytVh8en7dc3GrjkWtlmaXvkOMi3+p5qM1FGqdpL+LiruRSP2dFvPushZU+uvnWdWu5q7Stycbi6cdqfp5x5V0b0ldsq9Zviq8/H319yOpW1lc1/hNxpGOrgAxGBqoH1B2gJHkuvwxWJ72cgJTgyuTohVDpM7I2cWXd8HDtdnOf2xbH2qRm/Vl03ZV2LPZerZ9WfXddjandT2UNSJxz3d3umOYRc23RdVfayeoZGn3UcibXZF27frqxGSrzl5A4pV0da388vTkq8q3irM1FGmetz0gll9n4K3WH18JKH91867p7rIVK2/1Yzc8O3++IPvTno74GI1ndyvqqxn8ijrjzSAnLBu8Wk64j5cJrN3kpyW7gy+tyAuyC10mSe8u7d92Hez2X36nJ1+26GEy89oEPZVL7oT89Sa7dcD+Ut2POJl0v2rn8rtb/WjuGYuHYfoq8JPLx9PqprwGff5VHF7ueP18v3nflVZ7zuc/L+vJxHHn//Xba443ttPM1379K96QfvfbqsRn0XBqW9rIyISY7nvDajbUxR8Xcu/yHuNy42mte9+Huz+V9zsocuRh0jtRc5GVUjrprYVsf9XxLDlK7rp7NXW8t6Bxl11qxzq9rcxryqZ+1fK5m3ByE+yvzkZUN96M+ZPMc6qUx9Z7b43P4Zx5ukD7ofLGEQYVkpz/HbReCvi7/iZSebD2JvmyqGxIV8H9OPE+4n1Ahb8cvqnAvxNZdHDP5ghZsLvS9GbcA0r0r83DbGPSDW7zutJOhxhwXVNaPul6Q5avXjx930U6or+c2j93cM/nL514w87v0Z/vvtePbaI7Z9GHXSRZ/tiZasRnM+AXJQS5yIX6X6zC25U/jC601nc9RJipL2VS3u+Zn9HOYz3vvObNzERheC70+KveX/uS6nrPBtWBytNCLVe5la8Ezqg9r89HSh2Kes1hX9OHIHP9PslsayQYAS0OMAd5CBncee4B5AGwE84C7A+YB8NaAecDd4fTHVgAAcO84/c4DAADuHYPmYb/d8PZQfAsBAABOxuCx1R00j/h1vNbX8gAAYJhbP7Y61Q6h2e7lzn9/Ov5r7wMAwDD33jwud36nFP+19wEAYJwDjq3i1wr9b27G33Ds/VZo9lus4ZqUdcK/XM+Plpq/+Rp+izXVM/cBAOBkHPCBefz1+yj2/nU8GhLRrx0TFTsE+T0Q+zr+Xsj8c/rOu+7bG1O6F2LBPAAAboWDzUP/QlNmDGICld2ANQ+7G/Go3YfZYbj+tMEEWsdWAABwfI5wbJXu1wTcXZtFP+5CauZR/yA77CYWk1D9YR4AAGflZDuPy6sk7vp6IfJuh5LvNPyfHzZHU2En416H3Ujq25fN+uBPogAAnIzTHVtlx031Y6hY19WLZZXoZ9d3z/L+4rGYo/LnqTEPAICTwd+2AgCAYW799zwAAODug3kAAMAwHFsBAMAw7DwAAGAYzAMAAIbh2AoAAIZh5wEAAMNgHgAAMAzHVgAAMAw7DwAAGAbzAACAYTi2AgCAYdh5AADAMJgHAAAMw7EVAAAMw84DAACGwTwAAGAYjq0AAGAYdh4AADAM5gEAAMNwbAUAAMOw8wAAgGEwDwAAGIZjKwAAGIadBwAADIN5AADAMBxbAQDAMOw8AABgGMwDAACG4dgKAACGYecBAADDYB4AADAMx1YAADAMOw8AABgG8wAAgGE4tgIAgGHYeQAAwDCYBwAADMOx1S3w5z//T/U6AMBdhZ3HLfD1119XrwMA3FUwjxH+9NP0m0/+Wr/XAfPosGdOAeC8HH5s1X34/z69+3//nt5Z5afpPSlv2/roevrNl9fT+0t7v5/e++zf07t/Sq8/+OCv02+//Nf024/mn+f69fZNHSn32d/z16af7F6lPU0eT8kW83j/k3/lMW3B5mshz8l9zCkAnJexnceGhz7SMpT3PguiVLknFEKmREkEtmh3vr+Un3+O96VsvG7blBjenanFvRCFT/VfoxTeklXzEEGvxWCxeVDj9cxm7eJW4j9fv485BYDzctCxlTOCT0RcrmfhqImBiFhFRArCzsMRBFAEplrW4wVtLhv6dYLz2Qahq7zz7rISh7AmdH3zkPHOAt6LSQl4ezcnOaybx33MKQCcl72OrUQ4lgc8ClsUhOY7Sm8k+4pCbccS41j6VSJbFzofgy/TMzZlZjKu5piMiDbomYcfV8sQErVx6fF6WuZR5y7nFADOy9DOIxOWNWZxGCr/5U+z8Pmf14VIiZ5+1yuiVC3vxUjET37OBXeFTpuRNaFb/8wjin7t3swi4L2cyLjmHWBmHqn8fcspAJyXPY6tekIn4qSPoNT1T+rvNLN30sIilOraTO1dsovFvKONdWvvkt/7bC67SYhvb+fh2b7zyChy1dh53MOcAsB52ePYak3olEgE4rvTFplQDAhd3u58333+0hY6V6/RfhMROhVrjTWhWzcPQfJaE3NLS6Al74ebx13JKQCcl9PvPD6So5RZkBrvNLUgOYIQ5SJWoRaDErEtQifXq21XDPAQjrvzUDlexhKv9c3jPuUUAM7LfuZRFYeIEol4dj6LS72sp2Ye9l1x/YhlRvpw7Yy/S14/tok/a1EOfcV6+vOBBl3zCLnx8c39GJN1Ypxd65mHLqNivIc5BYDzctK/beXOw+VnEciBnYeIaRSjSE2UnLBqkQl1a+wjdEkgo9DlZSV219aK2PXM471PTD0zhiw3DmMe8lVaKZv1X5qHtHWfcgoA5+Wk37Za6nYESNACWZhJoC5KBiVimiRYeZn2eII4L8R3x2vl6nR3Hsu7/EBt59G4V45XxamE9z7mFADOyx7HVnecTOj675Lz6/uz7QPzO8wZcgoA54U/yX4L/O1vX1SvAwDcVR7ezgMAAA4G8wAAgGE4tgIAgGHYeQAAwDCYBwAADMOxFQAADMPOAwAAhsE8AABgmJMfW11c3Uxv3rzpsJsuszoX09VNui71b64uVFs309VFKn+50/Vj3Vb7tfsVbp5NF0sdAACw7L3z+OMf/7t63aLFv0TEXIn75a4u5hV2l6HOxbPpZhF7aU+by1fTrjCP+Fr/rMvNP2MeAABd9jaPX375ZZOBDO08ZvNoG01C2lzMw73eecMQ88mEv2YetRgMmAcAQJe9j61EZH/++edVAxndeUjZy11F0CO7rwrziHXbR2AzDUOotgUAAF323nmIIH/88cerBtI3j4AI/2wK8bWYR1XQ5YjKlIuGkpVrILEsJrTGxjYBAB4iB5mH/LtqICL4VpgraLNY23kU7btr7SOp3Lz6n2k0jQsAABYOOraSf8U0xDzERGwZzeUu/5ZU+XlEndWdi96NmJ1JNJTcDKTfuslEMA8AgD4H7TzWjKO7g7CE3cCmOnrnEA3jcudEX5uNtFUaDzsPAIBDOcg8tuw4PLVdRn3nYcW72HmIWVjzEENRO4742UZ9x8LOAwDgUPY+tvr11183Goc/OqruAEbMI5rETNZW+IZW/NkbwM10dRV+zo6xBHYeAACHsvfOY5NxBMGvi3HdPCyrn3k44ofllfaioeyeNT9Qr9IxGACAh87e5gEAAA8X/iQ7AAAMw84DAACGwTwAAGAYjq0AAGAYdh4AADAM5gEAAMNwbAUAAMOw8wAAgGEwDwAAGIZjKwAAGMbtPMRAAAAAtoJ5AADAIH+Y/h+0UdYKxoTKCgAAAABJRU5ErkJggg==)
